using CodexGame.SmokeTests;
using CodexGame.SmokeTests.Cards;
using CodexGame.SmokeTests.Distribution;
using CodexGame.SmokeTests.Halli;
using CodexGame.SmokeTests.Playable;
using CodexGame.SmokeTests.Poker;
using CodexGame.SmokeTests.Battle;
using CodexGame.SmokeTests.Localization;
using CodexGame.SmokeTests.Presentation;
using CodexGame.SmokeTests.Shop;
using CodexGame.SmokeTests.Items;
using CodexGame.SmokeTests.Rewards;
using CodexGame.SmokeTests.Development;

var tests = new TestHarness();

CardDeckTests.Run(tests);
PrototypeSkullPolicyTests.Run(tests);
CardStorageTests.Run(tests);
BellTimingTests.Run(tests);
HalliRuleTests.Run(tests);
HalliStageTests.Run(tests);
HalliRevealSequenceTests.Run(tests);
PrototypeHalliSessionTests.Run(tests);
PrivateCardDistributionTests.Run(tests);
PokerEvaluatorTests.Run(tests);
PokerJokerRulesTests.Run(tests);
PokerRoundSessionTests.Run(tests);
BattleRuleTests.Run(tests);
LocalizationCatalogTests.Run(tests);
GuideModalStateTests.Run(tests);
HealthPipViewStateTests.Run(tests);
RopeTimerViewStateTests.Run(tests);
PokerResultOverlayStateTests.Run(tests);
AcquiredCardFanLayoutTests.Run(tests);
HalliPileOverlapLayoutTests.Run(tests);
StageFlowPlanTests.Run(tests);
BarShopSessionTests.Run(tests);
NextStageTransitionGateTests.Run(tests);
RunInventoryTests.Run(tests);
PokerItemSessionTests.Run(tests);
ItemExpansion0125Tests.Run(tests);
ItemUsePresentationSessionTests.Run(tests);
StageItemRestrictionSessionTests.Run(tests);
PresentationFlow0124Tests.Run(tests);
FirstStartTutorialSessionTests.Run(tests);
StageRewardTests.Run(tests);
DevelopmentCheatTests.Run(tests);

return tests.Complete();
